# Model Configuration
model:
    arch: icnetBN
    is_batchnorm: True

# Data Configuration
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 1025
    img_cols: 2049
    path: '../data/Cityscapes/'
    is_norm: True

# Training Configuration
training:
    n_workers: 4
    train_iters: 35000
    batch_size: 4
    val_interval: 500
    print_interval: 25
    loss:
        name: multi_scale_cross_entropy
        size_average: True

    # Optmizer Configuration
    optimizer:
        name: sgd
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0001
       
    # Augmentations Configuration
    augmentations:
        hflip: 0.5                                     #[flip horizontally with chance p]
        vflip: 0.5                                     #[flip vertically with chance p]

    # LR Schedule Configuration
    lr_schedule:
        name: poly_lr

    # Resume from checkpoint  
    resume: icnetBN_cityscapes_trainval_90k.pth