# Model Configuration
model:
    arch: pspnet
    version: sunrgbd

# Data Configuration
data:
    dataset: sunrgbd
    train_split: training
    val_split: val
    img_rows: 473
    img_cols: 473
    path: '../data/sunrgbd'
    img_norm: True

# Training Configuration
training:
    n_workers: 0
    train_iters: 30000
    batch_size: 8
    val_interval: 500
    print_interval: 10
    loss:
        name: multi_scale_cross_entropy
        size_average: True
        scale_weight: [1, 0.4]

    # Optmizer Configuration
    optimizer:
        name: sgd
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0005
       
    # Augmentations Configuration
    augmentations:
        gamma: 0.5
        rotate: 60
        hflip: 0.5                                     #[flip horizontally with chance p]
        vflip: 0.5                                     #[flip vertically with chance p]

    # LR Schedule Configuration
    lr_schedule:
        name: multi_step
        milestones: [26000,30000]
        gamma: 0.1

    # Resume from checkpoint  
    resume:
#    resume: 'runs/icnet_sunrgbd./36340/icnetBN_sunrgbd_best_model.pkl'