# Model Configuration
model:
    arch: segnet

# Data Configuration
data:
    dataset: pascal 
    train_split: train
    val_split: val
    img_rows: 360
    img_cols: 480
    path: 'data/pascal//VOCdevkit/VOC2012'
    is_transform: True

# Training Configuration
training:
    n_workers: 4
    train_iters: 35000
    batch_size: 16
    val_interval: 500
    print_interval: 25
    loss:
        name: cross_entropy
        size_average: True

    # Optmizer Configuration
    optimizer:
        name: adam
        lr: 1.0e-3
        weight_decay: 0.0005
        momentum: 0.9
       
    # Augmentations Configuration
    augmentations:
        hflip: 0.5                                     #[flip horizontally with chance p]
        vflip: 0.5                                     #[flip vertically with chance p]

    # LR Schedule Configuration
    lr_schedule:
        name: multi_step
        milestones: [30000, 35000]
        gamma: 0.1